# Generated by Django 5.1.2 on 2024-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
