# Generated by Django 5.1.2 on 2024-10-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='task_id',
            field=models.CharField(max_length=255),
        ),
    ]
